### PR TITLE
Feature/db-migration

### PR DESCRIPTION
**Pull request by ciiidi**
Typeorm migrations using typeorm cli

### CODE REVIEW

**Comment by jmaicaaan** [comment]
Hi @ciiidi, well done on this one. The migrations works for both environment here in my local. I do have couple of questions, should we exclude the seeding from the migration? I thought we had this issue before when the seeding is joined with the migration? Also, I think we should also generate a migration file via command like `dbmigrate:create`. Thoughts? 🤔

**Comment by ciiidi** [comment]
Yeah I guess we can isolate the seeding on migrations, I am not sure if it is possible but we will give it a try. If it's okay let's have migration for now. Then we will add seeding support later.
On command that generates a migration file, are you pertaining on a npm run script? yeah we can do that too, that was I good idea because not all machines have an typeorm installed globally and it will centralized the version of typeorm cli that will be use.

**Comment by jmaicaaan** [comment]
Got it, let's add it into next release! This is already good and ready to merge but before that can we add the generation of migration? So we could finally have the complete initial code base for migration. 😉 Will it that take too long complete?

**Comment by ciiidi** [comment]
Hi @jmaicaaan I add run script for migration create. eg npm run dbmigrate:create -n NameOfMigration

**Comment by ciiidi** [comment]
@jmaicaaan the migrations are working fine when I test it I just edit the arrangement in initial schema I guess it is required.

**Comment by jmaicaaan** [comment]
Let me get back to you on that. Will test it tomorrow into another environment. The migrations on my machine yesterday was working fine too. I am not sure what causes it to fail awhile ago. Thanks for your work

**Pull request merged**
